#!/bin/bash

set -e

RED='\033[0;41;30m'
STD='\033[0;0;39m'
_VERSION="7.9"
 
pause(){
  read -p "Press [Enter] key to continue..." fackEnterKey
}

build(){
	echo "-Parameter #1 is \"$1\".-"
	echo $PWD
	cd $1
	sudo ./build
	cd ..
	
	# uncomment pause to see messages
	#pause
}

remove(){
	if [ -d "$1" ]; then
		sudo rm -rf $1
	fi
	
	# uncomment pause to see messages
	#pause
}
 
setup(){
	if [ -d "$1" ]; then
		sudo rm -rf $1
	fi

	sudo mkdir $1 && cd $1 && sudo lb config
	sudo cp /usr/share/doc/live-build/examples/auto/* auto/

	if [ ! -f "./build" ]; then
		cd ..
		sudo cp ./buildx ./$1/build
	fi
	
	# uncomment pause to see messages
	#pause
}

update(){
#	echo "-Parameter #1 is \"$1\".-"
	echo $PWD
	cd $1
	
	rm -rf ./auto/*
	cp -rf ~/star-live-build/common/auto/* ./auto/
	cd config

	if [ ! -d "bootloaders" ]; then
		mkdir bootloaders
	fi

	if [ ! -d "binary_debian-installer" ]; then
		mkdir binary_debian-installer
	fi

	rm -rf ./apt/*
	rm -rf ./archives/*
	rm -rf ./hooks/*
	rm -rf ./includes.chroot/*
	rm -rf ./package-lists/*
	rm -rf ./includes.installer/*
	rm -rf ./binary_debian-installer
	rm -rf ./bootloaders/*
	rm -rf ./includes.binary/*

	cp -r ~/star-live-build/common/config/* ./

	cp -r ~/star-live-build/$1-64/config/hooks/* ./hooks/
	cp -r ~/star-live-build/$1-64/config/includes.chroot/* ./includes.chroot/
	cp ~/star-live-build/$1-64/config/package-lists/* ./package-lists/

	sed -i -e 's/VERSION/'${_VERSION}'/g' ./includes.chroot/etc/hostname
	sed -i -e 's/VERSION/'${_VERSION}'/g' ./includes.chroot/etc/issue
	sed -i -e 's/VERSION/'${_VERSION}'/g' ./includes.chroot/etc/issue.net
	sed -i -e 's/VERSION/'${_VERSION}'/g' ./includes.chroot/etc/motd
	sed -i -e 's/VERSION/'${_VERSION}'/g' ./includes.chroot/etc/os-release
	
	#echo $1-"Updated"

	# uncomment pause to see messages
	#pause
}
 
subSetupRemove(){
	while :
	do

		clear
		echo -e "\t~~~~~~~~~~~~~~~~~~~~~"	
		echo -e "\t SETUP/REMOVE - M E N U"
		echo -e "\t~~~~~~~~~~~~~~~~~~~~~"
		echo " "
		echo -e "\t-- setup -- "
		echo -e "\t1. Xfce"
		echo -e "\t2. Fluxbox"
		echo -e "\t3. Openbox"
		echo " "
		echo -e "\t-- remove -- "
		echo -e "\t4. Xfce"
		echo -e "\t5. Fluxbox"
		echo -e "\t6. Openbox"
		echo " "
		echo -e "\tx. Main Menu"
		echo " "	
		
		local choice
		read -p "Enter choice [ 1 - 6] or x : " choice
		
		case $choice in
			1) setup "xfce" ;;
			2) setup "fb" ;;
			3) setup "ob" ;;
			4) remove "xfce" ;;
			5) remove "fb" ;;
			6) remove "ob" ;;
			x|x) break;;
			*) echo -e "\tinvalid answer, please try again" ;;
		esac
	done
}

subUpdateBuild(){
	while :
	do

		clear
		echo -e "\t~~~~~~~~~~~~~~~~~~~~~"	
		echo -e "\t UPDATE/BUILD - M E N U"
		echo -e "\t~~~~~~~~~~~~~~~~~~~~~"
		echo " "
		echo -e "\t-- update -- "
		echo -e "\t1. Xfce"
		echo -e "\t2. Fluxbox"
		echo -e "\t3. Openbox"
		echo " "
		echo -e "\t-- build -- "
		echo -e "\t4. Xfce"
		echo -e "\t5. Fluxbox"
		echo -e "\t6. Openbox"
		echo " "
		echo -e "\tx. Main Menu"
		echo " "	
		
		local choice
		read -p "Enter choice [ 1 - 6] or x : " choice
		
		case $choice in
			1) update "xfce" ;;
			2) update "fb" ;;
			3) update "ob" ;;
			4) build "xfce" ;;
			5) build "fb" ;;
			6) build "ob" ;;
			x|x) break;;
			*) echo -e "\tinvalid answer, please try again" ;;
		esac
	done
}

main(){
	clear
	echo -e "\t~~~~~~~~~~~~~~~~~~~~~"	
	echo -e "\t M A I N - M E N U"
	echo -e "\t~~~~~~~~~~~~~~~~~~~~~"
	echo " "
	echo -e "\t1. Setup/Remove"
	echo -e "\t2. Update/Build"
	echo " "
	echo -e "\tx. Exit"
	echo " "
		
	local choice
	read -p "Enter choice [ 1 - 2] or x : " choice
	
	case $choice in
		1) subSetupRemove ;;
		2) subUpdateBuild ;;
		x|x) break;;
		*) echo -e "\tinvalid answer, please try again" ;;
	esac
}
 
# ----------------------------------------------
# Step #3: Trap CTRL+C, CTRL+Z and quit singles
# ----------------------------------------------
trap '' SIGINT SIGQUIT SIGTSTP

while true
do
	main
done
