#!/bin/sh

if [ -d "ob" ]; then
	sudo rm -rf ob
fi

sudo mkdir ob && cd ob && sudo lb config
sudo cp /usr/share/doc/live-build/examples/auto/* auto/

cd ..

if [ ! -f "./build" ]; then
	cp ./buildx ./build
fi
sudo mv ./build ./ob
sudo chown root:root ./ob/build
sudo ./update-ob
