#!/bin/sh

if [ -d "xfce" ]; then
	sudo rm -rf xfce
fi

sudo mkdir xfce && cd xfce && sudo lb config
sudo cp /usr/share/doc/live-build/examples/auto/* auto/

cd ..

if [ ! -f "./build" ]; then
	cp ./buildx ./build
fi
sudo mv ./build ./xfce
sudo chown root:root ./xfce/build
sudo ./update-xfce
