#!/bin/sh

if [ -d "fb" ]; then
	sudo rm -rf fb
fi

sudo mkdir fb && cd fb && sudo lb config
sudo cp /usr/share/doc/live-build/examples/auto/* auto/

cd ..

if [ ! -f "./build" ]; then
	cp ./buildx ./build
fi
sudo mv ./build ./fb
sudo chown root:root ./fb/build
sudo ./update-fb
