#!/bin/sh

_VERSION="2.3"

# clear
echo "Version ["$_VERSION"]"
#echo -n "Check version and run? (Y|n) > "
#read a
#if [ "$a" = "y" ] || [ "$a" = "Y" ] || \
#[ "$a" = "" ]; then

cd jwm
rm -rf ./auto/*
cp -rf /home/simon/star-live-build/jwm-64/auto/* ./auto/
cd config

if [ ! -d "bootloaders" ]; then
	mkdir bootloaders
fi

#if [ ! -d "binary_debian-installer" ]; then
	#mkdir binary_debian-installer
#fi

rm -rf ./apt/*
rm -rf ./archives/*
rm -rf ./hooks/*
rm -rf ./includes.chroot/*
rm -rf ./package-lists/*
rm -rf ./includes.installer/*
# rm -rf ./binary_debian-installer
rm -rf ./bootloaders/*
rm -rf ./includes.binary/*

if [ ! -d "./includes.binary/install" ]; then
	mkdir ./includes.binary/install
fi

cp /home/simon/star-live-build/jwm-64/config/apt/* ./apt/
cp /home/simon/star-live-build/jwm-64/config/archives/* ./archives/
cp -r /home/simon/star-live-build/jwm-64/config/bootloaders/* ./bootloaders/

# cp -r /home/simon/star-live-build/jwm-64/config/binary_debian-installer .
cp -r /home/simon/star-live-build/jwm-64/config/includes.installer/* ./includes.installer/
cp /home/simon/star-live-build/jwm-64/config/includes.installer/preseed.cfg ./includes.binary/install

# cp -r /home/simon/star-live-build/openbox-64/config//includes.binary/* ./includes.binary/
# cp /home/simon/star-live-build/jwm-64/config/includes.installer/* ./includes.binary/install
cp -r /home/simon/star-live-build/jwm-64/config/hooks/* ./hooks/
cp -r /home/simon/star-live-build/jwm-64/config/includes.chroot/* ./includes.chroot/
cp /home/simon/star-live-build/jwm-64/config/package-lists/* ./package-lists/

sed -i -e 's/VERSION/'${_VERSION}'/g' ./includes.chroot/etc/hostname
sed -i -e 's/VERSION/'${_VERSION}'/g' ./includes.chroot/etc/issue
sed -i -e 's/VERSION/'${_VERSION}'/g' ./includes.chroot/etc/issue.net
sed -i -e 's/VERSION/'${_VERSION}'/g' ./includes.chroot/etc/motd
sed -i -e 's/VERSION/'${_VERSION}'/g' ./includes.chroot/etc/os-release

cd ../..

#fi
